---

version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: lockfile-only
    schedule:
      interval: "daily"  # Initial high freq for testing, will reset to "monthly" once we confirm it works
      day: "tuesday"
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
