---

version: 2
updates:

  # Note: Dependabot doesn't properly handle updating poetry lockfiles,
  # so the poetry lockfile is updated with GH actions instead.

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
