version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `poetry.lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    open-pull-requests-limit: 2
    schedule:
      interval: "daily"