ci:
  skip: [poetry-lock]  # Often fails on pre-commit.ci due to network issues
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '2.4.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock

  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        args: [--parallel, --in-place]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
        args: [--fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      # - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: debug-statements
