---

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py

# Optional additional formats
formats:
  - pdf

# Python environment
# Equivalent to: pip install resqpy
python:
  version: 3.8
  install:
    - method: pip
      path: .
    - requirements: docs/requirements-extras.txt
